version: '3'

services:
  # database:
  #   image: mariadb
  #   restart: always
  #   volumes:
  #     - ./:/app
  #   working_dir: /app
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     - MARIADB_USER=root
  #     - MARIADB_PASSWORD=root
  #     - MYSQL_DATABASE=VEHICLES
  #     - MARIADB_ROOT_PASSWORD=root

  app:
    image: node:hydrogen-alpine
    # depends_on:
    #   - database
    command: sh -c "npm install && npm run start"
    ports:
      - "3333:3000"
    volumes:
      - ./:/app
    working_dir: /app
