CREATE DATABASE VEHICLES;
USE VEHICLES;

CREATE TABLE COR(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR(30),
  HEX VARCHAR(6)
);

CREATE TABLE MARCA(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  DESCRICAO VARCHAR(50),
  SLOGAN VARCHAR(100),
  ANO_CRIACAO INT
);

CREATE TABLE MODELO(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  DESCRICAO VARCHAR(50),
  ANO INT,
  POLEGADA_RODA DECIMAL(3, 2),
  PESO DECIMAL(4, 2),
  MARCA_ID INT, FOREIGN KEY (MARCA) REFERENCES MARCA(ID)
);

CREATE TABLE VEICULO(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  PLACA VARCHAR(10),
  RENAVAM VARCHAR(11),
  COR_ID INT, FOREIGN KEY (COR) REFERENCES COR(ID),
  MODELO_ID INT, FOREIGN KEY (MODELO_ID) REFERENCES MODELO(ID)
);